version: "3.9"

services:
  db:
    image: postgres:16
    container_name: sma-backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sma_backend_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: sma-backend-assessment
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sma_backend_db?schema=public
      JWT_SECRET: change-me
      CLIENT_ORIGIN: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
